<div class="row">
    <div class="col-sm-12">
        <div class="portlet box blue">
        	<div class="portlet-title">
        		<div class="caption">
        			<i class="fa fa-gift"></i> Payslips
        		</div>
        		<div class="tools">
        			<a href="javascript:;" class="collapse" data-original-title="" title="">
        			</a>
        		</div>
        	</div>
        	<div class="portlet-body">
                @include('pagination.header_1')
            	<table class="table table-striped table-bordered table-hover">
                    <thead>
                	<tr>
                		<th>Date Generated</th>
						<th>Date Covered</th>
						<th>Generated By</th>
                		<th style="width:140px"></th>
                    </tr>			
                	</thead>
                	<tbody>
						<tr v-for="payslip in filtered1">
							<td>
								@{{ formatDateTime(payslip.created_at,"MM/DD/YYYY LT") }}
							</td>
							<td>
								@{{ formatDateTime(payslip.date_start,"MM/DD/YYYY") }} - @{{ formatDateTime(payslip.date_end,"MM/DD/YYYY") }}
							</td>
							<td>
								@{{ payslip.name }}
							</td>
							<td>
								<a v-bind:href="'../../payroll/previewSingle/' + payslip.id"
								   class="btn btn-md btn-info" target="_blank">View</a>
							</td>
						</tr>
                	</tbody>
                </table>
                @include('pagination.footer_1')
            </div>
        </div>
    </div>
</div>